# NOTE:
# If `labels: ['foo']` is not explicitly configured,
# Dependabot will not follow `labels: []`.
# https://github.com/dependabot/dependabot-core/issues/11783

version: 2

updates:
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    labels: ['build']
    commit-message:
      prefix: 'build'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    labels: ['ci']
    commit-message:
      prefix: 'ci'
      include: 'scope'
