# NOTE: Dependabot won't follow `labels: []`.
# https://github.com/dependabot/dependabot-core/issues/11783

version: 2

# TODO: Allow lower case commit message.
# https://github.com/dependabot/dependabot-core/issues/10586
updates:
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      # Runs every Monday.
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels: ['build']
    commit-message:
      prefix: 'build'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Runs every Monday.
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels: ['ci']
    commit-message:
      prefix: 'ci'
      include: 'scope'
