[match]
dot = true

[schedule]
linters = ["cargo-deny"]

[formatters]
cargo-fmt = ["**/*.rs"]
prettier = ["**/*.yml", "**/*.md", "**/*.json"]
tombi = ["**/*.toml"]
shfmt = ["etc/ci/*.sh"]

[linters]
cargo-deny = ["**/Cargo.toml", "**/Cargo.lock"]
typos = ["**/*", "!examples/**/*.png"]
cargo-msrv = ["**/*.rs", "**/Cargo.toml", "**/Cargo.lock"]
cargo-clippy = ["**/*.rs", "**/Cargo.toml", "**/Cargo.lock"]
yamllint = ["**/*.yml"]
actionlint = [".github/workflows/*.yml"]
zizmor = [".github/workflows/*.yml", ".github/dependabot.yml"]
ast-grep = ["**/*.rs"]
alex = ["**/*.md"]
markdownlint-cli2 = ["**/*.md"]
vale = ["**/*.md"]
tombi = ["**/*.toml"]
shellcheck = ["etc/ci/*.sh"]

[args.formatters]
cargo-fmt = ["--all"]

[args.linters]
cargo-clippy = ["--all-targets", "--keep-going", "--locked"]
yamllint = ["--strict"]
tombi = ["--error-on-warnings"]
