feat:
  - '/### Proposal Type\s{2}Enhancement/'
docs:
  - '/### Proposal Type\s{2}Documentation/'
test:
  - '/### Proposal Type\s{2}Test/'
refactor:
  - '/### Proposal Type\s{2}Refactor'
ci:
  - '/### Proposal Type\s{2}CI/'
build:
  - '/### Proposal Type\s{2}Build/'
perf:
  - '/### Proposal Type\s{2}Performance/'
examples:
  - '/### Proposal Type\s{2}Example/'
