feat:
  - '/### Proposal Type\s{2}Enhancements/'
docs:
  - '/### Proposal Type\s{2}Documentation/'
test:
  - '/### Proposal Type\s{2}Tests/'
refactor:
  - '/### Proposal Type\s{2}Refactors/'
ci:
  - '/### Proposal Type\s{2}CI/'
build:
  - '/### Proposal Type\s{2}Build/'
perf:
  - '/### Proposal Type\s{2}Performance/'
examples:
  - '/### Proposal Type\s{2}Examples/'
chore:
  - '/### Proposal Type\s{2}Chore/'
