feat:
  - '(\nEnhancement\n)'
docs:
  - '(\nDocumentation\n)'
test:
  - '(\nTest\n)'
refactor:
  - '(\nRefactor\n)'
ci:
  - '(\nCI\n)'
build:
  - '(\nBuild\n)'
perf:
  - '(\nPerformance\n)'
examples:
  - '(\nExample\n)'
