docs:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/*.md'
          - '.github/DISCUSSION_TEMPLATE/*.yml'
          - '.github/ISSUE_TEMPLATE/*.yml'
          - '.github/DCO'
          - 'LICENSE'
          - 'README.md'

chore:
  - changed-files:
      - any-glob-to-any-file:
          - '.config/**'
          - '.github/CODEOWNERS'
          - '.gitignore'
          - '.git-blame-ignore-revs'
          - '.editorconfig'
          # NOTE: `*.foo`, `/*.foo`, and `./*.foo` will trigger a recursive glob match.
          - '.vale.ini'
          - '.commitlintrc.json'
          - '.prettierrc.toml'
          - '.rustfmt.toml'
          - '.taplo.toml'
          - '.typos.toml'
          - '.markdownlint.yml'
          - '.yamllint.yml'
          - 'changelogithub.config.json'
          - 'rust-toolchain.toml'
          - 'deny.toml'
          - 'sgconfig.yml'

build:
  - changed-files:
      - any-glob-to-any-file:
          - 'Cargo.toml'
          - 'Cargo.lock'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/*.yml'
          - 'etc/ci/*.sh'
          - '.github/dco.yml'
          - '.github/dependabot.yml'
          - '.github/labeler.yml'
          - '.github/issue-labeler.yml'
          - '.github/title-labeler.yml'
          - '.github/insight.toml'

test:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'

examples:
  - changed-files:
      - any-glob-to-any-file:
          - 'examples/**'
