bug:
  - '(fix.*:)'
feat:
  - '(feat.*:)'
revert:
  - '(revert.*:)'
perf:
  - '(perf.*:)'
refactor:
  - '(refactor.*:)'
style:
  - '(style.*:)'
breaking:
  - '(!:)'
docs:
  - '(docs.*:)'
chore:
  - '(chore.*:)'
build:
  - '(build.*:)'
ci:
  - '(ci.*:)'
test:
  - '(test.*:)'
examples:
  - '(examples.*:)'
