bug:
  - '/^fix(?:\(([^)]+)\))?:\s.+/'
feat:
  - '/^feat(?:\(([^)]+)\))?:\s.+/'
revert:
  - '/^revert(?:\(([^)]+)\))?:\s.+/'
perf:
  - '/^perf(?:\(([^)]+)\))?:\s.+/'
refactor:
  - '/^refactor(?:\(([^)]+)\))?:\s.+/'
style:
  - '/^style(?:\(([^)]+)\))?:\s.+/'
breaking:
  - '/^(fix|feat|revert|perf|refactor|style|docs|chore|build|ci|test|examples)(?:\(([^)]+)\))?!:\s.+/'
docs:
  - '/^docs(?:\(([^)]+)\))?:\s.+/'
chore:
  - '/^chore(?:\(([^)]+)\))?:\s.+/'
build:
  - '/^build(?:\(([^)]+)\))?:\s.+/'
ci:
  - '/^ci(?:\(([^)]+)\))?:\s.+/'
test:
  - '/^test(?:\(([^)]+)\))?:\s.+/'
examples:
  - '/^examples(?:\(([^)]+)\))?:\s.+/'
