# https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
MD013: false
# NOTE:
# When Prettier formats the code, it follows this rule.
# If you turn it on, it can cause some problems.
# For example:
# 2. Create a new branch:
#    ```bash
#    git checkout -b MY_BRANCH_NAME origin/canary
#    ```
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md031.md
MD031: false
# NOTE:
# When Prettier formats the code, it follows this rule.
# Some special characters, like `✅`, can cause false positives.
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md060.md
MD060: false
