[package]
name = "katharsis"
version = "1.0.0-canary.30"
edition = "2024"
rust-version = "1.85.0"
description = "CLI tool for generating RSS feeds."
documentation = "https://docs.rs/katharsis"
homepage = "https://github.com/arghena/katharsis"
repository = "https://github.com/arghena/katharsis"
license = "MIT"
keywords = ["cli", "feed", "generator", "rss", "tool"]
categories = ["command-line-utilities"]
include = ["/LICENSE", "/src/"]

[[bin]]
name = "katharsis"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.43"
clap = { version = "4.5.55", features = ["derive", "env"] }
glob = "0.3.3"
inquire = "0.9.2"
rss = "2.0.12"
scraper = "0.25.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = [
  "fs",
  "io-util",
  "macros",
  "rt-multi-thread",
] }
toml = "0.9.11"
url = { version = "2.5.8", features = ["serde"] }

[dev-dependencies]
tokio-test = "0.4.5"

[lints.clippy]
pedantic = "warn"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(tarpaulin_include)"] }

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
