# Copyright (c) Tokio Contributors
# Distributed under the [MIT License](https://github.com/tokio-rs/tokio/blob/master/LICENSE).

[graph]
all-features = true

[licenses]
allow = ["MIT", "Apache-2.0", "MPL-2.0", "Unicode-3.0", "ISC", "BSD-3-Clause"]

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[advisories]
# TODO:
# Wait for `scraper` v0.24.0 update.
# https://github.com/rust-scraper/scraper/commit/6f076d1391cdb785f1d3128d3cbc21a649692184
ignore = ["RUSTSEC-2025-0057"]
