name: Report an issue
description: Report a Katharsis issue.
labels: ['bug']
type: Problem
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: input
    id: katharsis_version
    attributes:
      label: Katharsis Version
      description: What is the version number of your Katharsis?
      placeholder: for example, 1.0.0
    validations:
      required: true
  - type: input
    id: system_version
    attributes:
      label: System Version
      description: What is your system version?
      placeholder: for example, macOS 15.1.1
    validations:
      required: true
  - type: input
    id: minimal_reproduction_link
    attributes:
      label: Link to Minimal Reproduction Code for This Issue
      description: Please make sure to test on the latest canary version.
      placeholder: https://github.com/user/my-minimal-katharsis-issue-reproduction
    validations:
      required: true
  - type: textarea
    id: to_reproduce
    attributes:
      label: To Reproduce
      description: A step-by-step description of how to reproduce the issue.
      value: '1.'
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What were you expecting to happen?
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
    validations:
      required: true
  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: What additional information do you need to provide?
    validations:
      required: false
