name: Propose an improvement
description: Propose an improvement for Katharsis.
type: Task
body:
  - type: markdown
    attributes:
      value: Thanks for contributing to Katharsis, please go ahead and describe your proposal!
  - type: textarea
    attributes:
      label: Proposal Description
      description: The specific details of the proposal.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Rationale
      description: What problem does this proposal solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Approach
      description: How do we implement it?
    validations:
      required: false
