name: Action Analyzer

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    name: actionlint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install actionlint
        run: brew install actionlint
      - name: Run actionlint
        run: actionlint -verbose .github/workflows/*.yml
