name: Audit

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  insight:
    name: Insight
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Run Insight
        uses: arghena/insight@25649ff130c8733ba05cbb43328d42258072d26a # v0.1.0-canary.26
