name: Security Audit

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'deny.toml'

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    name: Run cargo deny
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cargo deny
        uses: EmbarkStudios/cargo-deny-action@v2
