name: Check Pull Request Title

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  insight:
    name: Insight
    if: ${{ github.event.action == 'opened' || github.event.changes.title != null }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Insight
        uses: arghena/insight@e8a9e1a4b0a95edf5614c3af333980d3c544e981 # v0.1.0-canary.48
        with:
          check-pull-request-title: true
