name: Check Pull Request Title

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  insight:
    name: Insight
    if: ${{ github.event.action == 'opened' || github.event.changes.title != null }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Insight
        uses: arghena/insight@af3676a74381d95b12c18993c0dd0e27fb06a9a6 # v0.1.0-canary.37
        with:
          check-pull-request-title: true
