name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha || github.run_id }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+', 'v[0-9]+.[0-9]+.[0-9]+-canary.[0-9]+']
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  insight:
    name: Insight
    runs-on: ubuntu-latest
    outputs:
      any-changed: ${{ steps.insight.outputs.any-changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Run Insight
        id: insight
        uses: arghena/insight@v0.1.0-canary.17
      - name: Upload to Coveralls
        if: ${{ github.ref_type == 'tag' }}
        uses: coverallsapp/github-action@v2
        with:
          file: './target/tarpaulin/lcov.info'

  unit_tests:
    name: Unit tests
    needs: insight
    if: ${{ github.ref_type == 'tag' || needs.insight.outputs.any-changed == 'true' }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - os: macos-latest
            target: aarch64-apple-darwin
            use-cross: false
          - os: macos-latest
            target: x86_64-apple-darwin
            use-cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use-cross: true
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            use-cross: true
          - os: ubuntu-latest
            target: arm-unknown-linux-gnueabihf
            use-cross: true
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use-cross: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}
      - name: Install cross
        if: matrix.job.use-cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Unit tests
        shell: bash
        run: |
          if [[ "${{ matrix.job.use-cross }}" == "true" ]]; then
            cross test --locked --target ${{ matrix.job.target }}
          else
            cargo test --locked --target ${{ matrix.job.target }}
          fi

  integration_tests:
    name: Integration tests
    needs: insight
    if: ${{ github.ref_type == 'tag' || needs.insight.outputs.any-changed == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build for release
        run: cargo build --release --locked --target ${{ matrix.target }}
      - name: End to end tests
        run: |
          cli="cargo run --release --locked --target ${{ matrix.target }}"

          $cli init
          $cli
