name: Commit Analyzer
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: commitlint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set nodejs
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/*
      - name: Install commitlint dependencies
        run: npm i @commitlint/config-conventional@latest
      - name: Validate PR title with commitlint
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo "$TITLE" | npx commitlint@latest -V
      - name: Validate PR commits with commitlint
        run: npx commitlint@latest -f ${{ github.event.pull_request.base.sha }} -t ${{ github.event.pull_request.head.sha }} -V
