name: Issue Labeler

on:
  issues:
    types: [ opened ]

jobs:
  labeler:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    name: Add labels
    strategy:
      matrix:
        label:
          - { prefix: "fix:", name: "bug" }
          - { prefix: "doc:", name: "documentation" }
          - { prefix: "feat:", name: "enhancement" }
          - { prefix: "ex:", name: "example" }
          - { prefix: "test:", name: "test" }
          - { prefix: "wf:", name: "workflow" }
          - { prefix: "dev:", name: "dev" }
    steps:
      - name: Add ${{ matrix.label.name }} label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.issue.title, matrix.label.prefix) }}
        with:
          labels: ${{ matrix.label.name }}
