name: JSON Analyzer
on:
  pull_request:
    paths:
      - 'changelogithub.config.json'
      - '.prettierrc.toml'
      - '.editorconfig'
jobs:
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set nodejs
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/*
      - name: Run prettier
        run: npx prettier@latest changelogithub.config.json -c
  jsonlint:
    name: jsonlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install jsonlint
        run: brew install jsonlint
      - name: Run jsonlint
        run: |
          shopt -s globstar
          jsonlint changelogithub.config.json -q
