name: Labeler
on:
  pull_request:
    types: [opened]
jobs:
  labeler:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Add PR label
    strategy:
      matrix:
        label:
          - { prefix: 'fix', name: 'bug' }
          - { prefix: 'chore', name: 'chore' }
          - { prefix: 'docs', name: 'documentation' }
          - { prefix: 'feat', name: 'enhancement' }
          - { prefix: 'build', name: 'build' }
          - { prefix: 'ci', name: 'ci' }
          - { prefix: 'revert', name: 'revert' }
          - { prefix: 'test', name: 'test' }
          - { prefix: 'pref', name: 'perf' }
          - { prefix: 'refactor', name: 'refactor' }
          - { prefix: 'style', name: 'style' }
    steps:
      - name: Add ${{ matrix.label.name }} label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, matrix.label.prefix) }}
        with:
          labels: ${{ matrix.label.name }}
