name: Markdown Lint
on:
  pull_request:
    paths:
      - '.github/**/*.md'
      - 'docs/**/*.md'
      - 'examples/**/*.md'
      - 'README.md'
jobs:
  alex:
    name: alex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set nodejs
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/*
      - name: Run alex
        run: |
          shopt -s globstar
          npx alex .github/**/*.md docs/**/*.md examples/**/*.md README.md
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set nodejs
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/*
      - name: Run prettier
        run: |
          shopt -s globstar
          npx prettier .github/**/*.md docs/**/*.md examples/**/*.md README.md -c
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set nodejs
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/*
      - name: Run markdownlint
        run: |
          shopt -s globstar
          npx markdownlint-cli2 .github/**/*.md docs/**/*.md examples/**/*.md README.md
  vale:
    name: vale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install vale
        run: brew install vale
      - name: Run vale
        run: |
          shopt -s globstar
          vale .github/**/*.md docs/**/*.md examples/**/*.md README.md
  languagetool:
    name: languagetool
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run languagetool
        uses: reviewdog/action-languagetool@v1
        with:
          patterns: '.github/**/*.md docs/**/*.md examples/**/*.md README.md'
