name: Pull Request Labeler

on:
  pull_request:
    types: [ opened ]

jobs:
  labeler:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Add labels
    strategy:
      matrix:
        label:
          - { prefix: "fix:", name: "bug" }
          - { prefix: "chore:", name: "chore" }
          - { prefix: "doc:", name: "documentation" }
          - { prefix: "feat:", name: "enhancement" }
          - { prefix: "ex:", name: "example" }
          - { prefix: "revert:", name: "revert" }
          - { prefix: "test:", name: "test" }
          - { prefix: "dep:", name: "dependency" }
          - { prefix: "act:", name: "action" }
          - { prefix: "wf:", name: "workflow" }
          - { prefix: "dev:", name: "dev" }
    steps:
      - name: Add ${{ matrix.label.name }} label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, matrix.label.prefix) }}
        with:
          labels: ${{ matrix.label.name }}
