name: TOML Analyzer
on:
  pull_request:
    paths:
      - 'examples/**/katharsis.config.toml'
      - 'src/cmd/katharsis.config.toml'
      - 'tests/katharsis.config.toml'
      - '.prettierrc.toml'
      - 'Cargo.toml'
      - 'deny.toml'
      - 'rust-toolchain.toml'
      - '.rustfmt.toml'
      - '.editorconfig'
      - '.typos.toml'
jobs:
  taplo:
    name: taplo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cargo-binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      - name: Run cargo-binstall
        run: cargo-binstall --locked --no-confirm taplo-cli
      - name: Run taplo fmt
        run: |
          shopt -s globstar
          taplo fmt examples/**/katharsis.config.toml src/cmd/katharsis.config.toml tests/katharsis.config.toml .prettierrc.toml Cargo.toml deny.toml rust-toolchain.toml .rustfmt.toml --check
      - name: Run taplo check
        run: |
          shopt -s globstar
          taplo check examples/**/katharsis.config.toml src/cmd/katharsis.config.toml tests/katharsis.config.toml .prettierrc.toml Cargo.toml deny.toml rust-toolchain.toml .rustfmt.toml
