name: TOML Analyzer
on:
  pull_request:
    paths:
      - '*.toml'
      - 'examples/**/katharsis.config.toml'
      - 'src/cmd/katharsis.config.toml'
      - 'tests/katharsis.config.toml'
jobs:
  taplo:
    name: taplo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install taplo-cli
        uses: taiki-e/install-action@v2
        with:
          # Uses `cargo-binstall` as a fallback
          # NOTE: https://github.com/taiki-e/install-action/blob/main/TOOLS.md
          tool: taplo-cli
      - name: Run taplo fmt
        run: |
          shopt -s globstar
          taplo fmt --check
      - name: Run taplo check
        run: |
          shopt -s globstar
          taplo check
