name: Triage issues

on:
  issues:
    types: [ labeled ]

jobs:
  triage:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    name: Triage via nissuer
    steps:
      - name: Nissuer
        uses: balazsorban44/nissuer@1.10.0
        with:
          label-comments: |
            {
              "good first issue": ".github/comments/good-first-issue.md",
              "cannot recreate": ".github/comments/cannot-recreate.md",
              "resolved": ".github/comments/resolved.md",
              "unclear": ".github/comments/unclear.md"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  close-issue:
    needs: triage
    runs-on: ubuntu-latest
    name: Close issue
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Close issue if resolved
        if: ${{ github.event.label.name == 'resolved' }}
        run: gh issue close ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
