name: Typos Analyzer

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  typos:
    runs-on: ubuntu-latest
    name: typos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install typos
        uses: taiki-e/install-action@v2
        with:
          tool: typos
      - name: Run typos
        run: typos --files && typos -v
