name: YAML Analyzer
on:
  pull_request:
    paths:
      - '*.yml'
      - '.github/**/*.yml'
      - '.config/**/*.yml'
      - '.prettierrc.toml'
      - '.editorconfig'
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install yamllint
        run: brew install yamllint
      - name: Run yamllint
        run: yamllint . --list-files && yamllint . -s
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set nodejs
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/*
      - name: Run prettier
        run: |
          shopt -s globstar
          npx prettier@latest .github/**/*.yml .config/**/*.yml ./.*.yml ./*.yml -c --no-error-on-unmatched-pattern --log-level debug
